name: C/C++ CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Valgrind
        run: |
          sudo apt-get install valgrind > /dev/null
          echo "Valgrind installed!"

      - name: Install libsdl2-dev
        run: |
          sudo apt-get install libsdl2-dev > /dev/null
          echo "libsdl2-dev installed!"

      - name: make check
        run: cd tests && make check_quiet
